[build]
  # 'base' की ज़रूरत नहीं है क्योंकि आपका कोड Root में है।
  
  # बिल्ड कमांड को Root में चलाएँ
  command = "npm run build"
  
  # आपका बिल्ड आउटपुट 'dist' फ़ोल्डर में जाएगा (मान लीजिए कि Create React App या Vite यही करता है)
  publish = "dist" 

# Node.js का आवश्यक वर्ज़न 18 सेट करें। यह आपकी पिछली build fail होने की समस्या ठीक करेगा।
[build.environment]
  NODE_VERSION = "18"
