[build]
  # Build settings (these match what you set in the UI)
  command = "npm run build"
  publish = "dist"

# Set the Node.js version explicitly
# We are using Node 18 here, which is stable for React/Vite.
[build.environment]
  NODE_VERSION = "18"